env:
  global:
    - REPO="client-v3"
    - CI_HOME=`pwd`/$REPO
os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
install:
  - cd client-v3
  - npm install
script:
  - cd client-v3
  - ng test --watch false
  - ng e2e
  - exit 0
