env:
  global:
    - REPO="client-v3"
    - CI_HOME=`pwd`/$REPO
language: node_js
node_js:
  - "node"
before_install:
  - echo TRAVIS_BUILD_DIR= ${TRAVIS_BUILD_DIR}
  - echo CI_HOME= ${CI_HOME}
  - cd $CI_HOME
install: npm install
before_script:
  - echo TRAVIS_BUILD_DIR= ${TRAVIS_BUILD_DIR}
  - echo CI_HOME= ${CI_HOME}
  - cd $CI_HOME
notifications:
  slack: rti:nBr3dvYD5mClKt1pAnuHgH8J
  email: false
